### PR TITLE
Update to Rails 6

### PR DESCRIPTION
**Pull request by xanderman**
Update dependencies to allow Rails 6.

I'm not aware of any code changes that need to come along with this. Seems to work fine in local testing. Please LMK if you know of anything I'm missing.

### CODE REVIEW

**Review by snapdocsalba — APPROVED** [review]

**Comment by evdevdev** [comment]
Hello Snapdocs Friends!

For some reason I'm getting notifications about changes to this repo. I'm thinking you might want to make it private, since it's leaking some data about the internal state of the snapdocs system? 

Admittedly, the data it is leaking is no big deal. But safety first, amiright?

**Comment by tycoool** [comment]
Hey @earnold nice to hear from you :) and thank you for the heads up! 

It seems that for security reasons Github doesn't allow the changing of visibility of forked repos 🤷

Screen Shot 2021-09-17 at 9 12 17 AM

**Comment by evdevdev** [comment]
@tycoool Hey Cris! Hope all is well!

Fun, cool hack: you can delete the repo in github, re-create it as a private one, push to it, and then voila! New private repo.

**Comment by tycoool** [comment]
@JuandissimoGrandissimo - please take a look at the convo in this thread and let me know if from a security standpoint we are better off following GitHub suggestion and keeping this forked repo public or it makes more sense to make it private. I did some research and there may be valid reasons to keep it public but you and your team are the experts so I defer to you.  Thank you!

**Pull request merged**
